### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by ashkon91** [kjan95129/build-a-cat#1]
Hey hey team .cat

Idea 1:
I think that the first idea really fits the theme of the course. Perhaps after getting the proposed idea completed you could take this a level farther and scrape data from animal shelters in the area and match the user up with the cat of the dreams that is in need of a home. 

Idea 2:
Once again I feel like this fits the theme but try and think of ways to make this application potentially a little more user interactive.

Idea 3:
I like how this is built up on the second idea. By scoping it down it will allow you to search for a more specific subset of ideas. 

In general I really like that your group is looking to take advantage of existing large datasets available on the internet. Personally I enjoy both the 1st and 3rd idea the most!

If you have any followup questions you can reply to this issue with (@ashkon91) or make a private piazza post and I'll be more than glad to help you all out!

Best,
Ashkon

**Comment by kjan95129** [comment]
Thanks for the advice! Going to go towards the cat idea.
